DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    major TEXT NOT NULL,
    credits INTEGER NOT NULL CHECK (credits >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    department TEXT NOT NULL,
    credits INTEGER NOT NULL CHECK (credits > 0),
    capacity INTEGER NOT NULL CHECK (capacity > 0)
);

CREATE TABLE IF NOT EXISTS enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'enrolled'
        CHECK (status IN ('enrolled', 'waitlisted', 'dropped', 'completed')),
    grade NUMERIC(5, 2) CHECK (grade BETWEEN 0 AND 100),
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, course_id)
);

INSERT INTO students (id, first_name, last_name, email, major, credits, active)
VALUES
    (1, 'Ada', 'Lovelace', 'ada.lovelace@example.edu', 'Computer Science', 96, TRUE),
    (2, 'Grace', 'Hopper', 'grace.hopper@example.edu', 'Computer Science', 120, TRUE),
    (3, 'Katherine', 'Johnson', 'katherine.johnson@example.edu', 'Mathematics', 105, TRUE),
    (4, 'Dorothy', 'Vaughan', 'dorothy.vaughan@example.edu', 'Mathematics', 88, TRUE),
    (5, 'Alan', 'Turing', 'alan.turing@example.edu', 'Computer Science', 72, FALSE)
ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    major = EXCLUDED.major,
    credits = EXCLUDED.credits,
    active = EXCLUDED.active;

INSERT INTO courses (id, code, title, department, credits, capacity)
VALUES
    (1, 'CSCI 1103', 'Introduction to Programming', 'Computer Science', 4, 30),
    (2, 'CSCI 3081', 'Program Design and Development', 'Computer Science', 4, 24),
    (3, 'MATH 2243', 'Linear Algebra', 'Mathematics', 3, 28),
    (4, 'STAT 3021', 'Introduction to Probability and Statistics', 'Statistics', 3, 35)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    title = EXCLUDED.title,
    department = EXCLUDED.department,
    credits = EXCLUDED.credits,
    capacity = EXCLUDED.capacity;

INSERT INTO enrollments (id, student_id, course_id, status, grade)
VALUES
    (1, 1, 2, 'enrolled', 94.50),
    (2, 1, 3, 'completed', 91.00),
    (3, 2, 2, 'enrolled', 98.00),
    (4, 3, 3, 'enrolled', 89.25),
    (5, 3, 4, 'completed', 92.75),
    (6, 4, 3, 'waitlisted', NULL),
    (7, 5, 1, 'dropped', NULL)
ON CONFLICT (id) DO UPDATE SET
    student_id = EXCLUDED.student_id,
    course_id = EXCLUDED.course_id,
    status = EXCLUDED.status,
    grade = EXCLUDED.grade;

SELECT setval(pg_get_serial_sequence('students', 'id'), (SELECT MAX(id) FROM students));
SELECT setval(pg_get_serial_sequence('courses', 'id'), (SELECT MAX(id) FROM courses));
SELECT setval(pg_get_serial_sequence('enrollments', 'id'), (SELECT MAX(id) FROM enrollments));
